# Generated by Django 3.1.4 on 2021-01-02 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='join_new',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='وقت الانضمام :'),
            preserve_default=False,
        ),
    ]
