# Generated by Django 3.1.4 on 2021-01-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210102_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specialist_doctor',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=100, null=True, verbose_name='التخصص : '),
        ),
    ]
