# Generated by Django 3.1.4 on 2021-01-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210102_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_new',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='وقت الانضمام :'),
            preserve_default=False,
        ),
    ]
