# Generated by Django 3.1.4 on 2021-01-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210103_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_new',
            field=models.DateTimeField(verbose_name='وقت الانضمام :'),
        ),
    ]
