# Generated by Django 3.1.4 on 2021-01-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210103_1517'),
        ('accounts', '0009_auto_20210103_1515'),
    ]

    operations = [
    ]
